name = "autograde"
version = "0.1.0"
defaultTargets = ["grade", "Autograde"]

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.21.0"

[[require]]
name = "Cli"
scope = "leanprover"
rev = "v4.21.0"

[[lean_lib]]
name = "Autograde"

[[lean_exe]]
name = "grade"
root = "Main"
supportInterpreter = true
